id: cbb30e3e177a472ca0107dbc9a845bd9
initial_creation_type: ocr
source_metadata:
  volumes:
    2a481e6dcb9a470484b3122b32632801:
      base_file: v024.txt
      image_group_id: I1PD95869
      title: ''
      total_pages: 1586
      volume_number: 24
